language: node_js
node_js:
- 12.16.1
install:
- npm install
script:
- npm run test
branches:
  only:
  - main
  - dev
deploy:
  provider: heroku
  api_key:
    secure: "xmbwbK/QXuUQj8hoUdSNalCAWWKpRNfcv2uaTMrN2CAHgsUC+a8Pic31NiCKcBElXagExY3iRU4iuCuWFO6vG5lI83Hspv9YHKZdHU/9Xri0HBOLxlBR1+vEYJdjKnw4WqazOKGBLel5F5ORYmoIVReyy1ERzu/g16qMMKXvaHtwepSYDp4TIbkTcFkCBMQUky4Hst2JkUD6mIzUF+g+ygwu3M7U2KQzWDdWM+LJCidb4dfpY0ZdF2Wn+uBVrH7T58TNBEnJLt/LvSHotwDDHqIDQj2HjeImZXdswiy10DwPRfWJtsQIlgYPc4eTHVhiVUaa/VWH6T/TnhxCMOPd9zVNKUlXygjmB2PK8Z/aX+XUqx1gBO/MH1CkqZXtqH5Lk+iuGaEPYWL7n+HuM/I5JU+hB/FR8UpxmNPYyhQztxqwF13+XT7bHWWj2qSYnNzRmPDmfn+vnQI4oZz7/PZLlFRVua4cWUjL/rFJ/aRsE8od562sBgGlM6rVtfR7hnTFXGSAHeESa1wm2nZ37gJpLyPGRA8K77Lrbr8ZSZZMZ4pR6VOaYGSaLSxfzMEmEXRO49T3krsoCqSS8WgnwkbnMb3as/9pEglllgemRbJp/YoOozS5g2mpOP2amG6U8kyBUoUYHCKygcFAvzn5ef376OLC5zSXUkYzafTPFrFm9/c="
  app:
    main: node-heroku-prod-vbooter
    dev: node-heroku-dev-vbooter





