language: node_js
node_js:
- 12.16.1
install:
- npm install
script:
- npm run test
branches:
  only:
  - main
  - dev
deploy:
  provider: heroku
  api_key:
    secure: pukivUb7LJMENBL6RZEEd4vmAmy8OdiLF0dtJH9P3qA86Y3l/njaZXX1WVoxRzl8TPL6/LMXooDxtnOgZYa7WshrxVa7cLU1LwUo3ayZ9FFEZnidjPKeneHM450ow4f1TsNTRP4GrnlBVGOmwwNIbO7akWQbnOA7ECdKdJhlOnzBJ0tcAgBFhV9Y1Nk/Nk6CSjfgsYiJKNCCCbEnvgqrAUGAxNEsAKhHToBsjIuCDIk1J60hYb1sra9OZA/cfEl0tY1npJieXLTNek5E7i2LjsyFkU+wLOgjEuFKtHnY30l5AXzOetm8+1klxW9pCTY4kQkPutE3w5SwkrY2YD9S6X/XAzoQaktn0BgwNx8YICEtsuLE1pZug0xQOSjYWGuHG/RMRY7Ev3WQyr1NrJ5dvV9aMPZA78MpZ8XexEvND4sa+5MP4ZxWhzed3tfpwv7IUNHdZ0biWt4hKzMq/FLDiPe9GgbFZXSMYOzXZcoSMupUdiebxtnte3ulrrkKOr7uFwMUYzcW+9QTrjotQA0MN+njmHOEXLM9UWTH5sJTyKvhhbYM0UAAyERHomkRkMqdvhCf+00BQMt4zq3B7XInDUzZ/llEPZ2wqZeHpeQ0widOWw6B+Rc1xfjJoG0XciLiURsklf6W0fOTEh9y2+d8y2c78CzCvlq+39Ezv/KmAis=
  app:
    main: node-heroku-prod-vbooter
    dev: node-heroku-dev-vbooter
